version: '3'

services:
    nginx:
        image: nginx:stable-alpine
        volumes:
            - "./www:/usr/share/nginx/html"
            - "./log:/var/log/nginx"
            - "./nginx.conf:/etc/nginx/nginx.conf"
        ports:
            - "80:80"

    web-php:
        build: .
        volumes:
            - "./www:/script"

    db:
        image: mysql
        restart: always
        environment:
            MYSQL_USER: emaloc
            MYSQL_PASSWORD: emaloc
            MYSQL_ROOT_PASSWORD: emaloc
        cap_add:
          - SYS_NICE

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
